services:
  better-auth-nest-db:
    image: postgres:alpine
    container_name: postgres
    restart: always
    environment:
      POSTGRES_DB: betterAuthNest
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - 5432:5432 # make sure you don't have another container running on DB_PORT
    # healthcheck:
    #   test: ['CMD-SHELL', 'pg_isready -d $${DB_NAME} -U $${DB_USER}']
    #   interval: 10s
    #   timeout: 30s
    #   retries: 5
    volumes:
      - ./data/db:/var/lib/postgresql/data
    attach: false
